### ISSUE TITLE
Create a Protocol Alternative to Control Sequences.

### ISSUE THREAD

**Issue by SRGOM** [railsware/upterm#1114]
I hope the world moves on from VT100/ANSI. The escape sequences, to horrible non-standard color support with little standardization on support detection-  everything is just horrendous and old fashioned. And don't get me started on handling of detection of current cursor position, I don't know whoever came up with that?

I know emulating it is required since all raw apps assume it, but given now cool upterm looks I hope you guys can lead with a startover.

Plus, thinking of it actually, not a lot of people use such apps, except those who "live" in terminal. 

Just saying.. I don't expect you to do anything about it.

**Comment by vlad-shatskyi** [comment]
I'm afraid you're right. We have too little resources to create a new communication protocol. The only related improvement we plan to implement is that all upterm built-in commands should print JSON instead of usual UNIX-way plain text, which then will be formatted using prettifiers if presented to a person, or piped as JSON further, if it's a part of a pipeline. 

By the way, there is an international standard describing control sequences: https://www.ecma-international.org/publications/standards/Ecma-048.htm

Also terminals implement the "thick server thin client" architecture, so in general case a server (process) shouldn't be asking a client (terminal emulator) its cursor position, it should always know the position.

**Comment by SRGOM** [comment]
> Server shouldn't ask client cursor position
You make a conceptual point that sounds good, but it seems to me that to implement programs like fzf which pop up a menu right where the cursor is, you need to know where the cursor is relative to the terminal.

I understand that the standard is out there, but, for example, it seems that there is no way to detect if a terminal supports 24 bit colors. Also, the standard is built on very old principles and not organically. And I shouldn't have to remember and understand how to output colorful messages. I should be able to do #ffaa00 to output orange, or even #ffaa0080 to output it half transparent. ESCAPED by a non-ugly looking escape sequence, like \x1b#<8bytes> would be color, \x1b!<...> should be something else and so on.
