### ISSUE TITLE
No Linux Version?

### ISSUE THREAD

**Issue by thiagolucio** [railsware/upterm#1307]
Dear Guys, 
Where I found a upterm-0.4.4-x86_64-linux.AppImage ?

**Comment by le0pard** [comment]
@thiagolucio you can build it. Automatic build on CI is not working and I cannot fix it right now, because credentials is encrypted and person, which did this cannot provide what exactly in this credentials.

**Comment by thiagolucio** [comment]
Thanks for your reply @le0pard . I gotcha that way and try it.

**Comment by rmmcnulty9** [comment]
Should this really be closed? It would be really nice if the CI could be fixed so AppImages are created.

**Comment by eliorc** [comment]
Not a node or electron developer, but would love to use Upterm - googled how to create AppImage from source code and couldn't figure it out - Anywhere to find Upterm 0.4.4 AppImage? I'm asking this because in 0.4.3 my `~/.bashrc` aliases and exports are not recognized and I'm hoping it is fixed in 0.4.4
