### ISSUE TITLE
Show status bar in Vim mode

### ISSUE THREAD

**Issue by thomasbritton** [railsware/upterm#446]
Would it be possible to show the vim status bar at the bottom of the view when in vim mode? 

As currently nothing is there

**Comment by shockone** [comment]
Now the info panel (not the one from vim) is present when vim is open.

**Comment by thomasbritton** [comment]
Ah this is a real shame, quite a blocker for me using this Terminal as I use Vim pretty much exclusively.

**Comment by shockone** [comment]
Are you saying that this yellow bar (probably yours is prettier, huh?) is missing for you? 
![](https://dl.dropboxusercontent.com/spa/dlqheu39w0arg9q/15_ygsgh.png)

**Comment by thomasbritton** [comment]
It doesn't look like that no.

It would be very cool if it did pick up my `.vimrc` file but all I see at the bottom of the screen is the following:

![screenshot 2016-06-08 13 19 06](https://cloud.githubusercontent.com/assets/272787/15894076/c1ac6cf8-2d7b-11e6-95f3-6009595c415a.png)

So when i hit `ESC` to type commands such as `:wq` etc I can't see whats happening.

This is from the latest version, `0.0.37 (0.0.37.117)`

**Comment by BlitzKraft** [comment]
I have the same issue. I am running commit 688bbff. Running anything with a terminal UI messes up everything. Upterm is responsive, just doesn't show it on screen. For example, when I run `man ls` I can navigate the page using arrow keys, but the only parts of the screen that contain the text are redrawn. Everything else just stays there like a text background. 

Due to this, the man page is almost unreadable. This happens with any application with a terminal UI, like htop, vim, less etc.

**Comment by vlad-shatskyi** [comment]
@BlitzKraft is it still like that with the latest master?

**Comment by BlitzKraft** [comment]
@vlad-shatskyi 

Just checked out the master. The issue is gone. The screen redraw works properly.
