### ISSUE TITLE
Customize UI

### ISSUE THREAD

**Issue by iDams** [railsware/upterm#447]
Is there a way to add my custom CSS for the UI?

**Comment by shockone** [comment]
There is not, but if you have any suggestion, we may try to implement them in Black Screen.

**Comment by iDams** [comment]
Right now, the only option I see is doing like Slack (which is also built with Electron): create a "Preference" tab in Black Screen menu and let people add custom colors.

This solution might take some time to develop. Not sure if it worth it or not.

**Comment by shockone** [comment]
But maybe you wanted to change or add something specific using custom CSS?

**Comment by iDams** [comment]
Hmm not really. 
I like to custom the tools I use in general so I was curious about it.
It's not essential though :)

**Comment by garfbargle** [comment]
Being able to change the background/text color would be nice. :)

**Comment by maebert** [comment]
Since Black Screen is targeted at developers anyway who probably won't shy away from some CSS themselves, it would be nice to just have it load a custom CSS after the original one. TaskPaper does this  reasonably well. I think the four options for this are

1. Look for a `~/.blackscreen.css` or `$XDG_CONFIG_HOME/black-screen/user.css`
2. Bundle a blank `user.css` file with the app, and preferably have a menu option that will show this file in Finder
3. Respect an environment variable that lets the user specify the location of a custom CSS file
4. Have a settings dialogue that lets the user specify the location of a custom CSS file

Personally, I prefer 1. or 3. as it makes it easier for me to have the same setup on different machines and keep my settings files in sync. Is there a technical challenge to loading two CSS files that I'm not aware of?

**Comment by iDams** [comment]
@maebert I was thinking about a solution like 1. too. Simple and also you could share your css with other people easily. But when I look into how the css is done, it's using inline style so no css classes. With the actual implementation, I don't think solution 1. is possible. Maybe you know a way of doing it?

**Comment by maebert** [comment]
Ah, well. Is that an issue with electron, or just something that will need to be refactored?

**Comment by derekblank** [comment]
I would love this feature. Personally I would want to use this with a different typeface and font size ([13px Inconsolata](http://www.levien.com/type/myfonts/inconsolata.html). I've forked the app to do so but would love if we added it as a config option instead. The inline styles are just React -- most of the main configuration is already abstracted in `main.ts`. We could easily pull out the remaining variables like typeface and colors, and let users customize with their own CSS or dotfile. 

cc/ @maebert @iDams @shockone

**Comment by kevinchau321** [comment]
Is there currently any way to change the font size?

**Comment by iDams** [comment]
@kevinchau321 Yep! You can change it in your `~/.hyper.js` file:
```
config: {
    // default font size in pixels for all tabs
    fontSize: 16,
    ...
}
```

**Comment by shockone** [comment]
Wrong terminal emulator, @iDams. ;)

Currently there is no way to change font size unless you are willing to change it in the source code. Moving forward I like Linux approach of having one value per file, like `~/something/black_screen/font_size` would contain just one value: 12.

**Comment by luco** [comment]
I don't say customizing css itself, but basic options, like `font-size`, `line-height` and colors are essentials for this. Each developer uses it's own setup and this would be awesome on BS.

**Comment by kevinchau321** [comment]
Changing font size is a must have feature for me, especially shortcuts like cmd+ and cmd- that change the window size and font size all at once (just like the built in mac terminal)

**Comment by luco** [comment]
@kevinchau321 Oh yeah, I forgot `cmd+`. Black Screen it's a helluva terminal emulator, and with these options, would kill.

**Comment by vlad-shatskyi** [comment]
Closing in favor of https://github.com/railsware/upterm/issues/1124
